In [1]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
psmfiles = os.listdir('PSMTables')

print(psmfiles)

#merging the files into 1 
all_psm = []
for file in psmfiles:
    df = (
        pd.read_csv(f'PSMTables/{file}',
                     delimiter="\t")
                     .assign(File = file.split("_")[0]) #function to add a column at the end with a shorter name
    )
    all_psm.append(df) #this is to add files together

def get_spectrum(row): #function to rename the spectrum id in the psm file dataframe
    spectra_raw = row.Spectrum
    return spectra_raw.split("_")[-1]

main_psm = (pd.concat(all_psm).assign(Spectrum_ID = lambda df: df.apply(get_spectrum, axis=1))
)

main_psm['File'] = main_psm['File'].astype(str)
main_psm['Spectrum_ID'] = main_psm['Spectrum_ID'].astype(int)

main_psm #main working psm df

['AB15_wHORMAD_1_PSMTable.txt', 'AB16_1_PSMTable.txt', 'AB18_1_PSMTable.txt', 'AB19_1_PSMTable.txt', 'MM01_1_PSMTable.txt', 'ZK01_1_PSMTable.txt']

,Sample,Spectrum,Peptide,Type,Length,Engine,PEPscore,FDR,Delta,UnambiguousMatch,Conflict,Annotation,Database,Search,Charge,Proteins,File,Spectrum_ID
0,AB15_HORMAD,AB15_HORMAD_306621,TLAELLVLL,REF,9,"mergedresults,comet",0.010983,0.001455,0.577278,True,"DLVSLLVLL[0.588261],TLAAVLQRL[0.999685],TLALLD...",".(iTRAQ8plex)TLAELLVLL,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,ERV_UP_8,gencod...",V1,1,ENST00000262225.7_1_12:124069096-124081273:+_1...,AB15,306621
1,AB15_HORMAD,AB15_HORMAD_271055,TLAELLVLL,REF,9,"mergedresults,comet",0.200767,0.034589,0.627694,True,"DLVSLLVLL[0.828461],ELVVSLVLL[0.991735],VVSELV...",".(iTRAQ8plex)TLAELLVLL,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,2,ENST00000262225.7_1_12:124069096-124081273:+_1...,AB15,271055
2,AB15_HORMAD,AB15_HORMAD_305795,SVLEQLFFV,REF,9,"mergedresults,comet",0.006372,0.000915,0.837839,True,"SVLFSHHRV[0.887986],FPLAAGLFFV[0.985618],DLLSQ...",".(iTRAQ8plex)SVLEQLFFV,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,1,"ENST00000506162.1_1_5:92927828-92929545:+_1,sp...",AB15,305795
3,AB15_HORMAD,AB15_HORMAD_305766,SVLEQLFFV,REF,9,"mergedresults,comet",0.015429,0.000915,0.544307,True,"LLLCGLFFV[0.803647],FPLAAGLFFV[0.718551],DLLSQ...",".(iTRAQ8plex)SVLEQLFFV,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,2,"ENST00000506162.1_1_5:92927828-92929545:+_1,sp...",AB15,305766
4,AB15_HORMAD,AB15_HORMAD_270375,SVLEQLFFV,REF,9,"mergedresults,comet",0.008191,0.000915,0.792738,True,"SVFSLPVSVF[0.934868],FPLAAGLFFV[0.954345],VLSS...",".(iTRAQ8plex)SVLEQLFFV,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,ERV_UP_8,gencod...",V1,2,"ENST00000506162.1_1_5:92927828-92929545:+_1,sp...",AB15,270375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,20220420_ZK,20220420_ZK_73342,ATLESVDLA,NOV,9,"mergedresults,comet",0.135519,0.008654,0.054782,True,"AELESLSLG[0.424017],AELDTVLTG[0.426321],AELESR...",".(iTRAQ8plex)ATLESVDLA,n[+304.205359999999985]...",gencode_pc_transcripts_7,V1,1,29_ENST00000674238_ENSG00000130119_F2_orf7,ZK01,73342
5699,20220420_ZK,20220420_ZK_73785,NFEDFEMVS,NOV,9,"mergedresults,comet",0.154117,0.010535,0.541637,True,"NTFASCSTDM[0.856167],NTFTHGMFY[1.0],NTAGSHGCAV...",".(iTRAQ8plex)NFEDFEM(Oxidation)VS,n[+304.20535...",gencode_pc_transcripts_7,V1,1,15_ENST00000510105_ENSG00000163104_F1_orf36,ZK01,73785
5700,20220420_ZK,20220420_ZK_153046,VENPKGFD,NOV,8,"mergedresults,comet",0.139003,0.008899,0.071699,True,"VENYLVSSLVS[0.791963],VENNKNST[0.337061],VENSM...",".(iTRAQ8plex)VENPK(iTRAQ8plex)GFD,n[+304.20535...",gencode_pc_transcripts_7,V1,2,11_ENST00000217740_ENSG00000101695_F0_orf22,ZK01,153046
5701,20220420_ZK,20220420_ZK_161842,LWSFLLKRNSLS,NOV,12,"mergedresults,comet",0.300434,0.044173,0.117117,True,"AELKALMFLLSLV[0.417551],CALVLLFLMLLFVLS[0.5966...",".(iTRAQ8plex)LWSFLLK(iTRAQ8plex)RNSLS,n[+304.2...","gencode_pc_transcripts_7,gencode_pc_transcripts_0",V1,3,"28_ENST00000360338_ENSG00000197714_F1_orf6,29_...",ZK01,161842
5702,20220420_ZK,20220420_ZK_190293,KLLDQLLKN,NOV,9,"mergedresults,comet",0.302965,0.044741,0.076219,True,"KLLDLLKLE[0.379184],KLLDLRKAQ[1.0],LKEVQLLGKG[...",.(iTRAQ8plex)K(iTRAQ8plex)LLDQLLK(iTRAQ8plex)N...,gencode_pc_transcripts_7,V1,3,25_ENST00000368865_ENSG00000154473_F0_orf61,ZK01,190293

In [3]:
p25files = os.listdir('C:/Users/Izadora/Documents/Project2/spectralclustering/p25_clusterfiles/rawclusters')

all_p25 = []

for file in p25files:
    df = (
        pd.read_csv(f'C:/Users/Izadora/Documents/Project2/spectralclustering/p25_clusterfiles/rawclusters/{file}', index_col=0)
    )
    all_p25.append(df)



filenames = {'AB15.mgf':'AB15',
             'AB16.mgf':'AB16',
             'AB18.mgf':'AB18',
             'AB19.mgf':'AB19',
             'ZK01.mgf':'ZK01',
             'MM01.mgf':'MM01'}

allp25 = (
    pd.concat(all_p25)
    .sort_values('Number of Files', ascending =False)
    .rename(columns = {'Number of Files':'FileCount', 'Filename':'File'})
    .replace({'File': filenames})

)


allp25['File'] = allp25['File'].astype(str)
allp25['Spectrum_ID'] = allp25['Spectrum_ID'].astype(int)

#this will be the working maracluster df
allp25

       File  Spectrum_ID  Cluster_ID  FileCount  Cluster_Size
156    AB15       166106        6348          6            34
290    AB16       103125        7386          6             9
301    AB19       217948        7449          6             9
300    AB19       297175        7449          6             9
299    AB16       103580        7449          6             9
...     ...          ...         ...        ...           ...
21479  AB18       301492       30625          2            20
21480  AB18       301252       30625          2            20
21481  AB19       574104       30625          2            20
21482  AB19       573800       30625          2            20
64423  ZK01       200752      102316          2             2

[80777 rows x 5 columns]

In [4]:
#mapping
p25_map = pd.merge(
    main_psm,
    allp25,
    how = 'right',
    on = ['File','Spectrum_ID']
)

#now we use this for the subcategorisation
p25_map

,Sample,Spectrum,Peptide,Type,Length,Engine,PEPscore,FDR,Delta,UnambiguousMatch,...,Annotation,Database,Search,Charge,Proteins,File,Spectrum_ID,Cluster_ID,FileCount,Cluster_Size
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB15,166106,6348,6,34
1,AB16,AB16_103125,EAAESMLC,NOV,8.0,"mergedresults,comet",0.023148,0.001034,0.028317,True,...,.(iTRAQ8plex)EAAESM(Oxidation)LC(Carbamidometh...,"gencode_pc_transcripts_3,gencode_pc_transcript...",V1,2.0,"185_ENST00000658780_ENSG00000110427_F2_orf134,...",AB16,103125,7386,6,9
2,AB19,AB19_217948,AEAATAFGA,REF,9.0,"mergedresults,comet",0.017068,0.000376,0.248160,True,...,".(iTRAQ8plex)AEAATAFGA,n[+304.205359999999985]...","gencode_pc_transcripts_5,ERV_UP_7,RiboSeq_nuOR...",V1,1.0,"32_ENST00000618555_ENSG00000124535_F2_orf1,sp_...",AB19,217948,7449,6,9
3,AB19,AB19_297175,AEAATAFGA,REF,9.0,"mergedresults,comet",0.024260,0.001655,0.538253,True,...,".(iTRAQ8plex)AEAATAFGA,n[+304.205359999999985]...","gencode_pc_transcripts_5,ERV_UP_7,ERV_UP_3,gen...",V1,1.0,"32_ENST00000618555_ENSG00000124535_F2_orf1,sp_...",AB19,297175,7449,6,9
4,AB16,AB16_103580,AEAATAFGA,REF,9.0,"mergedresults,comet",0.007132,0.000265,0.601359,True,...,".(iTRAQ8plex)AEAATAFGA,n[+304.205359999999985]...","ERV_UP_5,ERV_UP_8,ERV_UP_6,gencode_pc_transcri...",V1,1.0,"sp_Q96S55_WRIP1_HUMAN,32_ENST00000618555_ENSG0...",AB16,103580,7449,6,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB18,301492,30625,2,20
80773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB18,301252,30625,2,20
80774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB19,574104,30625,2,20
80775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB19,573800,30625,2,20
80776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ZK01,200752,102316,2,2

In [5]:
#load the PEAKS file, to compare with the psm mapped file, only using the alldeepnovo file, not including those from the reference databases

peaks = pd.read_csv(
    'C:/Users/Izadora/Documents/Project2/spectralclustering/PEAKS/alldeepnovo.csv',
    index_col=0
)

#just to differentiate between PSM peptides with PEAKS peptide
peaks1 = peaks.rename(columns={'Peptide':'Peaks_Peptide'})

peaks1

,File,Spectrum_ID,Peaks_Peptide,Tag length,SCORE (%),ALC (%),Length,m/z,z,RT,Delta RT,Area,Mass,ppm,PTM,local confidence (%),mode,tag(>=0.0%)
0,AB15,48167,LFEP,4,99.4,99.4,4,809.47644,1,121.9996,0.00,NaN,808.4655,4.5,TMT16plex,100 99 100 99,HCD,LFEP
1,AB15,41633,CYDALQK,7,99.1,99.1,7,753.41852,2,106.8556,0.00,NaN,1504.8206,1.3,Carbamidomethylation; TMT16plex,100 99 100 99 99 98 99,HCD,CYDALQK
2,AB15,4223,KDVEDEQEH,9,99.0,99.0,9,868.95190,2,17.2993,0.00,NaN,1735.8873,1.1,TMT16plex,93 100 100 100 100 100 99 100 100,HCD,KDVEDEQEH
3,AB15,172562,HLDVGGHMY,9,99.0,99.9,9,444.89423,3,498.4120,-1.10,NaN,1331.6617,-0.6,TMT16plex,100 100 100 100 100 100 100 100 100,HCD,HLDVGGHMY
4,AB15,166861,EEVEVYRH,8,98.9,99.7,8,455.57578,3,485.2783,-1.21,NaN,1363.7057,-0.1,TMT16plex,100 100 100 100 100 100 99 99,HCD,EEVEVYRH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1487,MM01,30494,TAATPET,7,60.1,74.4,7,497.77191,2,108.9876,-19.18,NaN,993.5303,-1.1,TMT16plex,63 73 89 96 47 60 92,HCD,TAATPET
1488,MM01,161208,LEEYVTPQLSL,11,60.1,68.1,11,798.44672,2,488.8695,-15.67,NaN,1594.8778,0.6,TMT16plex,75 81 87 80 95 86 24 26 29 76 91,HCD,LEEYVTPQLSL
1489,MM01,64227,DRVE,4,60.0,60.0,4,411.73389,2,214.5730,0.00,NaN,821.4568,-4.3,TMT16plex,91 27 44 79,HCD,DRVE
1490,MM01,63966,QSDPTQSGMY,10,60.0,67.0,10,709.33429,2,213.8160,14.86,NaN,1416.6516,1.7,TMT16plex,26 27 58 58 64 66 87 89 96 98,HCD,QSDPTQSGMY
1491,MM01,133580,NPPLLSLE,8,60.0,70.8,8,593.85358,2,412.2195,17.40,NaN,1185.6930,-0.3,TMT16plex,51 41 55 72 78 76 95 98,HCD,NPPLLSLE

In [28]:
#merge the peaks with the p25_map to have the peptides in the same file

merge = pd.merge(
    p25_map,
    peaks1,
    how = 'left',
    on = ['File','Spectrum_ID']
)   

merge.to_csv('allp25_matrix/all_p25_PSMPEAKS.csv')

In [29]:
merge #now we use this to do the clustering

,Sample,Spectrum,Peptide,Type,Length_x,Engine,PEPscore,FDR,Delta,UnambiguousMatch,...,z,RT,Delta RT,Area,Mass,ppm,PTM,local confidence (%),mode,tag(>=0.0%)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AB16,AB16_103125,EAAESMLC,NOV,8.0,"mergedresults,comet",0.023148,0.001034,0.028317,True,...,2.0,365.4208,13.36,NaN,1229.5592,-1.1,Carbamidomethylation; Oxidation (M); TMT16plex,76 80 87 95 99 99 50 56,HCD,AEAESMCL
2,AB19,AB19_217948,AEAATAFGA,REF,9.0,"mergedresults,comet",0.017068,0.000376,0.248160,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AB19,AB19_297175,AEAATAFGA,REF,9.0,"mergedresults,comet",0.024260,0.001655,0.538253,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AB16,AB16_103580,AEAATAFGA,REF,9.0,"mergedresults,comet",0.007132,0.000265,0.601359,True,...,1.0,366.5112,-5.31,NaN,1111.5834,1.9,TMT16plex,76 81 86 88 90 94 92 79 86,HCD,AEAATAFGA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
merge.columns

Index(['Sample', 'Spectrum', 'Peptide', 'Type', 'Length_x', 'Engine',
       'PEPscore', 'FDR', 'Delta', 'UnambiguousMatch', 'Conflict',
       'Annotation', 'Database', 'Search', 'Charge', 'Proteins', 'File',
       'Spectrum_ID', 'Cluster_ID', 'FileCount', 'Cluster_Size',
       'Peaks_Peptide', 'Tag length', 'SCORE (%)', 'ALC (%)', 'Length_y',
       'm/z', 'z', 'RT', 'Delta RT', 'Area', 'Mass', 'ppm', 'PTM',
       'local confidence (%)', 'mode', 'tag(>=0.0%)'],
      dtype='object')

In [31]:
#clean the df so that only the relevent info is there

clean = merge[['Cluster_ID','Cluster_Size','Peptide','Type','PEPscore',
                'FDR','Delta','Conflict','Annotation', 'Database','Charge','Proteins',
                'Peaks_Peptide','SCORE (%)','ALC (%)','m/z', 'z', 'RT', 'Delta RT',
                'FileCount','Spectrum_ID','File',]]

clean

,Cluster_ID,Cluster_Size,Peptide,Type,PEPscore,FDR,Delta,Conflict,Annotation,Database,...,Peaks_Peptide,SCORE (%),ALC (%),m/z,z,RT,Delta RT,FileCount,Spectrum_ID,File
0,6348,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,166106,AB15
1,7386,9,EAAESMLC,NOV,0.023148,0.001034,0.028317,"AAEESWSM[0.0514648],AETEGMWS[0.463177],EAAESCP...",.(iTRAQ8plex)EAAESM(Oxidation)LC(Carbamidometh...,"gencode_pc_transcripts_3,gencode_pc_transcript...",...,AEAESMCL,73.6,80.2,615.78625,2.0,365.4208,13.36,6,103125,AB16
2,7449,9,AEAATAFGA,REF,0.017068,0.000376,0.248160,"AEATAASTS[0.657044],ATAAAEFQ[0.265228],AAEAGPH...",".(iTRAQ8plex)AEAATAFGA,n[+304.205359999999985]...","gencode_pc_transcripts_5,ERV_UP_7,RiboSeq_nuOR...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,217948,AB19
3,7449,9,AEAATAFGA,REF,0.024260,0.001655,0.538253,"AEATAASTS[0.562513],SSPATATSS[0.978679],AAEAGP...",".(iTRAQ8plex)AEAATAFGA,n[+304.205359999999985]...","gencode_pc_transcripts_5,ERV_UP_7,ERV_UP_3,gen...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,297175,AB19
4,7449,9,AEAATAFGA,REF,0.007132,0.000265,0.601359,"AEATAASTS[0.608491],APSSTASST[0.960592],ARDATF...",".(iTRAQ8plex)AEAATAFGA,n[+304.205359999999985]...","ERV_UP_5,ERV_UP_8,ERV_UP_6,gencode_pc_transcri...",...,AEAATAFGA,84.3,85.9,1112.59277,1.0,366.5112,-5.31,6,103580,AB16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80772,30625,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,301492,AB18
80773,30625,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,301252,AB18
80774,30625,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,574104,AB19
80775,30625,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,573800,AB19
80776,102316,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,200752,ZK01

In [32]:
#let's check how many clusters and novel peptides found there are in these files

cluster_count = clean['Cluster_ID'].nunique()

print('Number of filtered clusters for p25 in 2-6 files:', cluster_count)


#check the number of peptides in this clusters
peptide_count = clean[['Cluster_ID','Peptide','Type']].drop_duplicates()

peptide_count = peptide_count['Type'].value_counts()

print('Type of peptides:',peptide_count)

Number of filtered clusters for p25 in 2-6 files: 20897
Type of peptides: Type
REF      5928
NOV      1248
DECOY     117
VAR        24
Name: count, dtype: int64

In [33]:
#number of clusters for each file

cluster2 = clean.loc[clean['FileCount']==2].groupby(by='Cluster_ID')
cluster3 = clean.loc[clean['FileCount']==3].groupby(by='Cluster_ID')
cluster4 = clean.loc[clean['FileCount']==4].groupby(by='Cluster_ID')
cluster5 = clean.loc[clean['FileCount']==5].groupby(by='Cluster_ID')
cluster6 = clean.loc[clean['FileCount']==6].groupby(by='Cluster_ID')

print (len(cluster2)), 
print (len(cluster3)), 
print (len(cluster4)), 
print (len(cluster5)), 
print (len(cluster6))

18609
1553
588
81
66

In [34]:
#make into different clusters for ease of mapping later
cluster2 = clean.loc[clean['FileCount']==2]
cluster3 = clean.loc[clean['FileCount']==3]
cluster4 = clean.loc[clean['FileCount']==4]
cluster5 = clean.loc[clean['FileCount']==5]
cluster6 = clean.loc[clean['FileCount']==6]

In [35]:
#categorise into 2: fully unidentified and identified

group = clean.groupby('Cluster_ID').count().reset_index()

group

,Cluster_ID,Cluster_Size,Peptide,Type,PEPscore,FDR,Delta,Conflict,Annotation,Database,...,Peaks_Peptide,SCORE (%),ALC (%),m/z,z,RT,Delta RT,FileCount,Spectrum_ID,File
0,1686,10,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,10,10,10
1,1699,11,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,11,11,11
2,1944,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,3,3
3,1945,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,2,2
4,1946,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,9,9,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20892,102306,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,2,2
20893,102307,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,2,2
20894,102308,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,2,2
20895,102309,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,2,2
20896,102316,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,2,2

In [36]:
#for fully unidentified, we can say those with 0 peptides

unid = group.loc[group['Peptide']==0]

unid_clusters = unid[['Cluster_ID']]

unid_clusters #now use this to map onto the clusters and check how many there are

       Cluster_ID
0            1686
1            1699
2            1944
3            1945
4            1946
...           ...
20892      102306
20893      102307
20894      102308
20895      102309
20896      102316

[14010 rows x 1 columns]

In [37]:
#map for fully uniden

A = unid_clusters
B = cluster2
C = cluster3
D = cluster4
E = cluster5
F = cluster6

unid_2 = A[A.Cluster_ID.isin(B.Cluster_ID)]
unid_3 = A[A.Cluster_ID.isin(C.Cluster_ID)]
unid_4 = A[A.Cluster_ID.isin(D.Cluster_ID)]
unid_5 = A[A.Cluster_ID.isin(E.Cluster_ID)]
unid_6 = A[A.Cluster_ID.isin(F.Cluster_ID)]


print('Unidentified (2) clusters=', len(unid_2))
print('Unidentified (3) clusters=', len(unid_3))
print('Unidentified (4) clusters=', len(unid_4))
print('Unidentified (5) clusters=', len(unid_5))
print('Unidentified (6) clusters=', len(unid_6))
print('total unidentified clusters in p25 = ', len(unid_2)+len(unid_3)+len(unid_4)+len(unid_5)+len(unid_6))

Unidentified (2) clusters= 13281
Unidentified (3) clusters= 535
Unidentified (4) clusters= 153
Unidentified (5) clusters= 21
Unidentified (6) clusters= 20
total unidentified clusters in p25 =  14010

In [38]:
#merge

unid_file2 = pd.merge(
    cluster2,
    unid_2,
    how = 'right',
    on = 'Cluster_ID'
)
unid_file3 = pd.merge(
    cluster3,
    unid_3,
    how = 'right',
    on = 'Cluster_ID'
)
unid_file4 = pd.merge(
    cluster4,
    unid_4,
    how = 'right',
    on = 'Cluster_ID'
)
unid_file5 = pd.merge(
    cluster5,
    unid_5,
    how = 'right',
    on = 'Cluster_ID'
)
unid_file6 = pd.merge(
    cluster6,
    unid_6,
    how = 'right',
    on = 'Cluster_ID'
)


#save these files
unid_file2.to_excel('allp25_matrix/fully_unid_clust(2).xlsx')
unid_file3.to_excel('allp25_matrix/fully_unid_clust(3).xlsx')
unid_file4.to_excel('allp25_matrix/fully_unid_clust(4).xlsx')
unid_file5.to_excel('allp25_matrix/fully_unid_clust(5).xlsx')
unid_file6.to_excel('allp25_matrix/fully_unid_clust(6).xlsx')

In [39]:
#filter out all the unidentified from the cluster df, this will be used from now on

filter_unid2 = cluster2[~cluster2.Cluster_ID.isin(unid_file2.Cluster_ID)]
filter_unid3 = cluster3[~cluster3.Cluster_ID.isin(unid_file3.Cluster_ID)]
filter_unid4 = cluster4[~cluster4.Cluster_ID.isin(unid_file4.Cluster_ID)]
filter_unid5 = cluster5[~cluster5.Cluster_ID.isin(unid_file5.Cluster_ID)]
filter_unid6 = cluster6[~cluster6.Cluster_ID.isin(unid_file6.Cluster_ID)]

In [40]:
#now we wanna filter into peptide counts
pep_fil2 = filter_unid2.groupby(by='Cluster_ID').nunique().reset_index()
pep_fil3 = filter_unid3.groupby(by='Cluster_ID').nunique().reset_index()
pep_fil4 = filter_unid4.groupby(by='Cluster_ID').nunique().reset_index()
pep_fil5 = filter_unid5.groupby(by='Cluster_ID').nunique().reset_index()
pep_fil6 = filter_unid6.groupby(by='Cluster_ID').nunique().reset_index()

#specify the identified/partial peptide clusters list
id_clust2 = pep_fil2.loc[pep_fil2['Peptide']==1]
id_clust3 = pep_fil3.loc[pep_fil3['Peptide']==1]
id_clust4 = pep_fil4.loc[pep_fil4['Peptide']==1]
id_clust5 = pep_fil5.loc[pep_fil5['Peptide']==1]
id_clust6 = pep_fil6.loc[pep_fil6['Peptide']==1]

#extract out all of the id and par clusters
par_id2 = filter_unid2[filter_unid2.Cluster_ID.isin(id_clust2.Cluster_ID)]
par_id3 = filter_unid3[filter_unid3.Cluster_ID.isin(id_clust3.Cluster_ID)]
par_id4 = filter_unid4[filter_unid4.Cluster_ID.isin(id_clust4.Cluster_ID)]
par_id5 = filter_unid5[filter_unid5.Cluster_ID.isin(id_clust5.Cluster_ID)]
par_id6 = filter_unid6[filter_unid6.Cluster_ID.isin(id_clust6.Cluster_ID)]

In [41]:
#extract only the partial clusters!
par2 = par_id2[par_id2['Peptide'].isna()]
par3 = par_id3[par_id3['Peptide'].isna()]
par4 = par_id4[par_id4['Peptide'].isna()]
par5 = par_id5[par_id5['Peptide'].isna()]
par6 = par_id6[par_id6['Peptide'].isna()]


print('Partial (2) clusters=', len(par2.groupby('Cluster_ID')))
print('Partial (3) clusters=', len(par3.groupby('Cluster_ID')))
print('Partial (4) clusters=', len(par4.groupby('Cluster_ID')))
print('Partial (5) clusters=', len(par5.groupby('Cluster_ID')))
print('Partial (6) clusters=', len(par6.groupby('Cluster_ID')))

Partial (2) clusters= 960
Partial (3) clusters= 104
Partial (4) clusters= 34
Partial (5) clusters= 0
Partial (6) clusters= 4

In [42]:
#now merge with the original cluster df

p2 = par_id2[par_id2.Cluster_ID.isin(par2.Cluster_ID)]
p3 = par_id3[par_id3.Cluster_ID.isin(par3.Cluster_ID)]
p4 = par_id4[par_id4.Cluster_ID.isin(par4.Cluster_ID)]
p5 = par_id5[par_id5.Cluster_ID.isin(par5.Cluster_ID)]
p6 = par_id6[par_id6.Cluster_ID.isin(par6.Cluster_ID)]

In [43]:
#save the files
p2.to_excel('allp25_matrix/partial_clust(2).xlsx')
p3.to_excel('allp25_matrix/partial_clust(3).xlsx')
p4.to_excel('allp25_matrix/partial_clust(4).xlsx')
p5.to_excel('allp25_matrix/partial_clust(5).xlsx')
p6.to_excel('allp25_matrix/partial_clust(6).xlsx')

In [44]:
#for the fully identified, we can filter out from the p2-p6

id2 = par_id2[~par_id2.Cluster_ID.isin(par2.Cluster_ID)]
id3 = par_id3[~par_id3.Cluster_ID.isin(par3.Cluster_ID)]
id4 = par_id4[~par_id4.Cluster_ID.isin(par4.Cluster_ID)]
id5 = par_id5[~par_id5.Cluster_ID.isin(par5.Cluster_ID)]
id6 = par_id6[~par_id6.Cluster_ID.isin(par6.Cluster_ID)]


print('Identified (2) clusters=', len(id2.groupby('Cluster_ID')))
print('Identified (3) clusters=', len(id3.groupby('Cluster_ID')))
print('Identified (4) clusters=', len(id4.groupby('Cluster_ID')))
print('Identified (5) clusters=', len(id5.groupby('Cluster_ID')))
print('Identified (6) clusters=', len(id6.groupby('Cluster_ID')))

Identified (2) clusters= 4111
Identified (3) clusters= 830
Identified (4) clusters= 376
Identified (5) clusters= 57
Identified (6) clusters= 37

In [45]:
#save the files
id2.to_excel('allp25_matrix/fully_id_clust(2).xlsx')
id3.to_excel('allp25_matrix/fully_id_clust(3).xlsx')
id4.to_excel('allp25_matrix/fully_id_clust(4).xlsx')
id5.to_excel('allp25_matrix/fully_id_clust(5).xlsx')
id6.to_excel('allp25_matrix/fully_id_clust(6).xlsx')

In [46]:
#now for the mismatch clusters
fil_id2 = filter_unid2[~filter_unid2.Cluster_ID.isin(par_id2.Cluster_ID)]
fil_id3 = filter_unid3[~filter_unid3.Cluster_ID.isin(par_id3.Cluster_ID)]
fil_id4 = filter_unid4[~filter_unid4.Cluster_ID.isin(par_id4.Cluster_ID)]
fil_id5 = filter_unid5[~filter_unid5.Cluster_ID.isin(par_id5.Cluster_ID)]
fil_id6 = filter_unid6[~filter_unid6.Cluster_ID.isin(par_id6.Cluster_ID)]

In [47]:
print('Mismatch (2) clusters=', len(fil_id2.groupby('Cluster_ID')))
print('Mismatch (3) clusters=', len(fil_id3.groupby('Cluster_ID')))
print('Mismatch (4) clusters=', len(fil_id4.groupby('Cluster_ID')))
print('Mismatch (5) clusters=', len(fil_id5.groupby('Cluster_ID')))
print('Mismatch (6) clusters=', len(fil_id6.groupby('Cluster_ID')))

Mismatch (2) clusters= 257
Mismatch (3) clusters= 84
Mismatch (4) clusters= 25
Mismatch (5) clusters= 3
Mismatch (6) clusters= 5

In [48]:
#save the files
fil_id2.to_excel('allp25_matrix/mismatch_clust(2).xlsx')
fil_id3.to_excel('allp25_matrix/mismatch_clust(3).xlsx')
fil_id4.to_excel('allp25_matrix/mismatch_clust(4).xlsx')
fil_id5.to_excel('allp25_matrix/mismatch_clust(5).xlsx')
fil_id6.to_excel('allp25_matrix/mismatch_clust(6).xlsx')