In [1]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#to locate all the files

psmfiles = os.listdir('PSMTables/')

psmfiles

['AB15_wHORMAD_1_PSMTable.txt',
 'AB16_1_PSMTable.txt',
 'AB18_1_PSMTable.txt',
 'AB19_1_PSMTable.txt',
 'MM01_1_PSMTable.txt',
 'ZK01_1_PSMTable.txt']

In [3]:
psmfiles = os.listdir('PSMTables')

print(psmfiles)

#merging the files into 1 
all_psm = []
for file in psmfiles:
    df = (
        pd.read_csv(f'PSMTables/{file}',
                     delimiter="\t")
                     .assign(File = file.split("_")[0]) #function to add a column at the end with a shorter name
    )
    all_psm.append(df) #this is to add files together

def get_spectrum(row): #function to rename the spectrum id in the psm file dataframe
    spectra_raw = row.Spectrum
    return spectra_raw.split("_")[-1]

main_psm = (pd.concat(all_psm).assign(Spectrum_ID = lambda df: df.apply(get_spectrum, axis=1))
)

main_psm

['AB15_wHORMAD_1_PSMTable.txt', 'AB16_1_PSMTable.txt', 'AB18_1_PSMTable.txt', 'AB19_1_PSMTable.txt', 'MM01_1_PSMTable.txt', 'ZK01_1_PSMTable.txt']

,Sample,Spectrum,Peptide,Type,Length,Engine,PEPscore,FDR,Delta,UnambiguousMatch,Conflict,Annotation,Database,Search,Charge,Proteins,File,Spectrum_ID
0,AB15_HORMAD,AB15_HORMAD_306621,TLAELLVLL,REF,9,"mergedresults,comet",0.010983,0.001455,0.577278,True,"DLVSLLVLL[0.588261],TLAAVLQRL[0.999685],TLALLD...",".(iTRAQ8plex)TLAELLVLL,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,ERV_UP_8,gencod...",V1,1,ENST00000262225.7_1_12:124069096-124081273:+_1...,AB15,306621
1,AB15_HORMAD,AB15_HORMAD_271055,TLAELLVLL,REF,9,"mergedresults,comet",0.200767,0.034589,0.627694,True,"DLVSLLVLL[0.828461],ELVVSLVLL[0.991735],VVSELV...",".(iTRAQ8plex)TLAELLVLL,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,2,ENST00000262225.7_1_12:124069096-124081273:+_1...,AB15,271055
2,AB15_HORMAD,AB15_HORMAD_305795,SVLEQLFFV,REF,9,"mergedresults,comet",0.006372,0.000915,0.837839,True,"SVLFSHHRV[0.887986],FPLAAGLFFV[0.985618],DLLSQ...",".(iTRAQ8plex)SVLEQLFFV,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,1,"ENST00000506162.1_1_5:92927828-92929545:+_1,sp...",AB15,305795
3,AB15_HORMAD,AB15_HORMAD_305766,SVLEQLFFV,REF,9,"mergedresults,comet",0.015429,0.000915,0.544307,True,"LLLCGLFFV[0.803647],FPLAAGLFFV[0.718551],DLLSQ...",".(iTRAQ8plex)SVLEQLFFV,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,2,"ENST00000506162.1_1_5:92927828-92929545:+_1,sp...",AB15,305766
4,AB15_HORMAD,AB15_HORMAD_270375,SVLEQLFFV,REF,9,"mergedresults,comet",0.008191,0.000915,0.792738,True,"SVFSLPVSVF[0.934868],FPLAAGLFFV[0.954345],VLSS...",".(iTRAQ8plex)SVLEQLFFV,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,ERV_UP_8,gencod...",V1,2,"ENST00000506162.1_1_5:92927828-92929545:+_1,sp...",AB15,270375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,20220420_ZK,20220420_ZK_73342,ATLESVDLA,NOV,9,"mergedresults,comet",0.135519,0.008654,0.054782,True,"AELESLSLG[0.424017],AELDTVLTG[0.426321],AELESR...",".(iTRAQ8plex)ATLESVDLA,n[+304.205359999999985]...",gencode_pc_transcripts_7,V1,1,29_ENST00000674238_ENSG00000130119_F2_orf7,ZK01,73342
5699,20220420_ZK,20220420_ZK_73785,NFEDFEMVS,NOV,9,"mergedresults,comet",0.154117,0.010535,0.541637,True,"NTFASCSTDM[0.856167],NTFTHGMFY[1.0],NTAGSHGCAV...",".(iTRAQ8plex)NFEDFEM(Oxidation)VS,n[+304.20535...",gencode_pc_transcripts_7,V1,1,15_ENST00000510105_ENSG00000163104_F1_orf36,ZK01,73785
5700,20220420_ZK,20220420_ZK_153046,VENPKGFD,NOV,8,"mergedresults,comet",0.139003,0.008899,0.071699,True,"VENYLVSSLVS[0.791963],VENNKNST[0.337061],VENSM...",".(iTRAQ8plex)VENPK(iTRAQ8plex)GFD,n[+304.20535...",gencode_pc_transcripts_7,V1,2,11_ENST00000217740_ENSG00000101695_F0_orf22,ZK01,153046
5701,20220420_ZK,20220420_ZK_161842,LWSFLLKRNSLS,NOV,12,"mergedresults,comet",0.300434,0.044173,0.117117,True,"AELKALMFLLSLV[0.417551],CALVLLFLMLLFVLS[0.5966...",".(iTRAQ8plex)LWSFLLK(iTRAQ8plex)RNSLS,n[+304.2...","gencode_pc_transcripts_7,gencode_pc_transcripts_0",V1,3,"28_ENST00000360338_ENSG00000197714_F1_orf6,29_...",ZK01,161842
5702,20220420_ZK,20220420_ZK_190293,KLLDQLLKN,NOV,9,"mergedresults,comet",0.302965,0.044741,0.076219,True,"KLLDLLKLE[0.379184],KLLDLRKAQ[1.0],LKEVQLLGKG[...",.(iTRAQ8plex)K(iTRAQ8plex)LLDQLLK(iTRAQ8plex)N...,gencode_pc_transcripts_7,V1,3,25_ENST00000368865_ENSG00000154473_F0_orf61,ZK01,190293

In [5]:
#main_psm.to_csv('all_psmscores.csv')

In [4]:
p30files = os.listdir('C:/Users/Izadora/Documents/Project2/spectralclustering/p30_clusterfiles/rawclusters')

all_p30 = []

for file in p30files:
    df = (
        pd.read_csv(f'C:/Users/Izadora/Documents/Project2/spectralclustering/p30_clusterfiles/rawclusters/{file}', index_col=0)
    )
    all_p30.append(df)

In [5]:
filenames = {'AB15.mgf':'AB15',
             'AB16.mgf':'AB16',
             'AB18.mgf':'AB18',
             'AB19.mgf':'AB19',
             'ZK01.mgf':'ZK01',
             'MM01.mgf':'MM01'}

allp30 = (
    pd.concat(all_p30)
    .sort_values('Number of Files', ascending =False)
    .rename(columns = {'Number of Files':'FileCount', 'Filename':'File'})
    .replace({'File': filenames})

)

In [6]:
allp30['File'] = allp30['File'].astype(str)
allp30['Spectrum_ID'] = allp30['Spectrum_ID'].astype(int)

#this will be the working maracluster df
allp30

       File  Spectrum_ID  Cluster_ID  FileCount  Cluster_Size
141    AB15       188249        5075          6             9
98     MM01        68440        4563          6            13
96     AB18       111709        4563          6            13
95     AB18       111513        4563          6            13
94     AB15       181255        4563          6            13
...     ...          ...         ...        ...           ...
13289  AB18       301730       17618          2            14
13290  AB19       573799       17618          2            14
13291  AB19       574407       17618          2            14
13292  AB19       555389       17618          2            14
39868  ZK01       166578       67289          2             2

[48358 rows x 5 columns]

In [7]:
main_psm['File'] = main_psm['File'].astype(str)
main_psm['Spectrum_ID'] = main_psm['Spectrum_ID'].astype(int)

#this is the working psm df
main_psm

,Sample,Spectrum,Peptide,Type,Length,Engine,PEPscore,FDR,Delta,UnambiguousMatch,Conflict,Annotation,Database,Search,Charge,Proteins,File,Spectrum_ID
0,AB15_HORMAD,AB15_HORMAD_306621,TLAELLVLL,REF,9,"mergedresults,comet",0.010983,0.001455,0.577278,True,"DLVSLLVLL[0.588261],TLAAVLQRL[0.999685],TLALLD...",".(iTRAQ8plex)TLAELLVLL,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,ERV_UP_8,gencod...",V1,1,ENST00000262225.7_1_12:124069096-124081273:+_1...,AB15,306621
1,AB15_HORMAD,AB15_HORMAD_271055,TLAELLVLL,REF,9,"mergedresults,comet",0.200767,0.034589,0.627694,True,"DLVSLLVLL[0.828461],ELVVSLVLL[0.991735],VVSELV...",".(iTRAQ8plex)TLAELLVLL,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,2,ENST00000262225.7_1_12:124069096-124081273:+_1...,AB15,271055
2,AB15_HORMAD,AB15_HORMAD_305795,SVLEQLFFV,REF,9,"mergedresults,comet",0.006372,0.000915,0.837839,True,"SVLFSHHRV[0.887986],FPLAAGLFFV[0.985618],DLLSQ...",".(iTRAQ8plex)SVLEQLFFV,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,1,"ENST00000506162.1_1_5:92927828-92929545:+_1,sp...",AB15,305795
3,AB15_HORMAD,AB15_HORMAD_305766,SVLEQLFFV,REF,9,"mergedresults,comet",0.015429,0.000915,0.544307,True,"LLLCGLFFV[0.803647],FPLAAGLFFV[0.718551],DLLSQ...",".(iTRAQ8plex)SVLEQLFFV,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,2,"ENST00000506162.1_1_5:92927828-92929545:+_1,sp...",AB15,305766
4,AB15_HORMAD,AB15_HORMAD_270375,SVLEQLFFV,REF,9,"mergedresults,comet",0.008191,0.000915,0.792738,True,"SVFSLPVSVF[0.934868],FPLAAGLFFV[0.954345],VLSS...",".(iTRAQ8plex)SVLEQLFFV,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,ERV_UP_8,gencod...",V1,2,"ENST00000506162.1_1_5:92927828-92929545:+_1,sp...",AB15,270375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,20220420_ZK,20220420_ZK_73342,ATLESVDLA,NOV,9,"mergedresults,comet",0.135519,0.008654,0.054782,True,"AELESLSLG[0.424017],AELDTVLTG[0.426321],AELESR...",".(iTRAQ8plex)ATLESVDLA,n[+304.205359999999985]...",gencode_pc_transcripts_7,V1,1,29_ENST00000674238_ENSG00000130119_F2_orf7,ZK01,73342
5699,20220420_ZK,20220420_ZK_73785,NFEDFEMVS,NOV,9,"mergedresults,comet",0.154117,0.010535,0.541637,True,"NTFASCSTDM[0.856167],NTFTHGMFY[1.0],NTAGSHGCAV...",".(iTRAQ8plex)NFEDFEM(Oxidation)VS,n[+304.20535...",gencode_pc_transcripts_7,V1,1,15_ENST00000510105_ENSG00000163104_F1_orf36,ZK01,73785
5700,20220420_ZK,20220420_ZK_153046,VENPKGFD,NOV,8,"mergedresults,comet",0.139003,0.008899,0.071699,True,"VENYLVSSLVS[0.791963],VENNKNST[0.337061],VENSM...",".(iTRAQ8plex)VENPK(iTRAQ8plex)GFD,n[+304.20535...",gencode_pc_transcripts_7,V1,2,11_ENST00000217740_ENSG00000101695_F0_orf22,ZK01,153046
5701,20220420_ZK,20220420_ZK_161842,LWSFLLKRNSLS,NOV,12,"mergedresults,comet",0.300434,0.044173,0.117117,True,"AELKALMFLLSLV[0.417551],CALVLLFLMLLFVLS[0.5966...",".(iTRAQ8plex)LWSFLLK(iTRAQ8plex)RNSLS,n[+304.2...","gencode_pc_transcripts_7,gencode_pc_transcripts_0",V1,3,"28_ENST00000360338_ENSG00000197714_F1_orf6,29_...",ZK01,161842
5702,20220420_ZK,20220420_ZK_190293,KLLDQLLKN,NOV,9,"mergedresults,comet",0.302965,0.044741,0.076219,True,"KLLDLLKLE[0.379184],KLLDLRKAQ[1.0],LKEVQLLGKG[...",.(iTRAQ8plex)K(iTRAQ8plex)LLDQLLK(iTRAQ8plex)N...,gencode_pc_transcripts_7,V1,3,25_ENST00000368865_ENSG00000154473_F0_orf61,ZK01,190293

In [8]:
print(len(main_psm))
print(len(allp30))

66952
48358

In [15]:
#extract the peptide list from the PSM table

psm_pep = main_psm[['Peptide']]

psm_pep1 = main_psm[['Peptide']].drop_duplicates()

psm_pep1.to_csv('PSM_peptidelist.txt')

In [14]:
print(len(psm_pep))
print(len(psm_pep1))

66952
19324

In [17]:
#mapping of the psm table to the maraclust
p30_mapping = pd.merge(
    main_psm,
    allp30,
    how = 'right',
    on = ['File','Spectrum_ID']
)

In [20]:
#p30_mapping.to_csv('all_p30_mapped.csv')

#extract the peptide list mapped p30 file with psm

p30_peptidelist_psm = p30_mapping[['Peptide']].drop_duplicates()

p30_peptidelist_psm.to_csv('P30_PSM_peptidelist.txt')

In [21]:
#this represents all the clusters in the p30 files, excluding those of single cluster sizes
p30_mapping

,Sample,Spectrum,Peptide,Type,Length,Engine,PEPscore,FDR,Delta,UnambiguousMatch,...,Annotation,Database,Search,Charge,Proteins,File,Spectrum_ID,Cluster_ID,FileCount,Cluster_Size
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB15,188249,5075,6,9
1,20220420_MM,20220420_MM_68440,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.028707,0.001514,0.494802,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","ERV_UP_8,gencode_pc_transcripts_0,Human+Ecoli_...",V1,1.0,"sp_Q8IZQ5_SELH_HUMAN,UTR5_ENSG00000211450_ENST...",MM01,68440,4563,6,13
2,AB18,AB18_111709,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.048350,0.001954,0.423707,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","gencode_pc_transcripts_1,gencode_pc_transcript...",V1,1.0,"sp_Q8IZQ5_SELH_HUMAN,1_ENST00000534355_ENSG000...",AB18,111709,4563,6,13
3,AB18,AB18_111513,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.050874,0.001466,0.691760,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","gencode_pc_transcripts_1,gencode_pc_transcript...",V1,1.0,"sp_Q8IZQ5_SELH_HUMAN,1_ENST00000534355_ENSG000...",AB18,111513,4563,6,13
4,AB15_HORMAD,AB15_HORMAD_181255,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.023348,0.002185,0.495534,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,1.0,"ENST00000534355.5_1_11:57508824-57509287:+_1,E...",AB15,181255,4563,6,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB18,301730,17618,2,14
48354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB19,573799,17618,2,14
48355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB19,574407,17618,2,14
48356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB19,555389,17618,2,14
48357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ZK01,166578,67289,2,2

In [ ]:
#later we can work out specifically how to do the categorisation for the p25 and p20 files, but let's focus on the p30 files first and work downwards

In [22]:
#let's filter it to be much smaller, where there are only files 4-6, as these are the clusters we are most interested in

p30_filtered = p30_mapping.loc[p30_mapping['FileCount']>3]
p30_filtered #use this as the main file to do the categorisation

,Sample,Spectrum,Peptide,Type,Length,Engine,PEPscore,FDR,Delta,UnambiguousMatch,...,Annotation,Database,Search,Charge,Proteins,File,Spectrum_ID,Cluster_ID,FileCount,Cluster_Size
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB15,188249,5075,6,9
1,20220420_MM,20220420_MM_68440,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.028707,0.001514,0.494802,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","ERV_UP_8,gencode_pc_transcripts_0,Human+Ecoli_...",V1,1.0,"sp_Q8IZQ5_SELH_HUMAN,UTR5_ENSG00000211450_ENST...",MM01,68440,4563,6,13
2,AB18,AB18_111709,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.048350,0.001954,0.423707,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","gencode_pc_transcripts_1,gencode_pc_transcript...",V1,1.0,"sp_Q8IZQ5_SELH_HUMAN,1_ENST00000534355_ENSG000...",AB18,111709,4563,6,13
3,AB18,AB18_111513,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.050874,0.001466,0.691760,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","gencode_pc_transcripts_1,gencode_pc_transcript...",V1,1.0,"sp_Q8IZQ5_SELH_HUMAN,1_ENST00000534355_ENSG000...",AB18,111513,4563,6,13
4,AB15_HORMAD,AB15_HORMAD_181255,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.023348,0.002185,0.495534,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,1.0,"ENST00000534355.5_1_11:57508824-57509287:+_1,E...",AB15,181255,4563,6,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985,AB18,AB18_115245,VEDPVTVEY,REF,9.0,"mergedresults,comet",0.000734,0.000295,0.740285,True,...,".(iTRAQ8plex)VEDPVTVEY,n[+304.205359999999985]...","gencode_pc_transcripts_1,gencode_pc_transcript...",V1,1.0,"sp_O14818_PSA7_HUMAN,sp_Q8TAA3_PSMA8_HUMAN,15_...",AB18,115245,4878,4,4
2986,AB19,AB19_266571,VEDPVTVEY,REF,9.0,"mergedresults,comet",0.000124,0.000139,0.522088,True,...,".(iTRAQ8plex)VEDPVTVEY,n[+304.205359999999985]...","TCGA_ChiTaRS_combined_fusion_ORF_aa,gencode_pc...",V1,1.0,"FUSION_ENST00000308271-ENST00000308268,FUSION_...",AB19,266571,4878,4,4
2987,AB15_HORMAD,AB15_HORMAD_185903,ALDSTNVEL,REF,9.0,"mergedresults,comet",0.000887,0.000915,0.626719,True,...,".(iTRAQ8plex)ALDSTNVEL,n[+304.205359999999985]...","gencode_pc_transcripts_3,ERV_UP_5,TCGA_ChiTaRS...",V1,1.0,"sp_P57735_RAB25_HUMAN,FUSION_ENST00000368273-E...",AB15,185903,4893,4,6
2988,AB19,AB19_223326,ALDSTNVEL,REF,9.0,"mergedresults,comet",0.001054,0.000139,0.398766,True,...,".(iTRAQ8plex)ALDSTNVEL,n[+304.205359999999985]...","TCGA_ChiTaRS_combined_fusion_ORF_aa,gencode_pc...",V1,1.0,"FUSION_ENST00000368273-ENST00000361084,FUSION_...",AB19,223326,4893,4,6
2989,AB16,AB16_110570,ALDSTNVEL,REF,9.0,"mergedresults,comet",0.001270,0.000265,0.715195,True,...,".(iTRAQ8plex)ALDSTNVEL,n[+304.205359999999985]...","ERV_UP_5,ERV_UP_8,ERV_UP_6,gencode_pc_transcri...",V1,1.0,"sp_P57735_RAB25_HUMAN,ENSP00000354376.5_ENST00...",AB16,110570,4893,4,6

In [24]:
#load the PEAKS file, to compare with the psm mapped file, only using the alldeepnovo file, not including those from the reference databases

peaks = pd.read_csv(
    'C:/Users/Izadora/Documents/Project2/spectralclustering/PEAKS/alldeepnovo.csv',
    index_col=0
)

#just to differentiate between PSM peptides with PEAKS peptide
peaks1 = peaks.rename(columns={'Peptide':'Peaks_Peptide'})

peaks1

,File,Spectrum_ID,Peaks_Peptide,Tag length,SCORE (%),ALC (%),Length,m/z,z,RT,Delta RT,Area,Mass,ppm,PTM,local confidence (%),mode,tag(>=0.0%)
0,AB15,48167,LFEP,4,99.4,99.4,4,809.47644,1,121.9996,0.00,NaN,808.4655,4.5,TMT16plex,100 99 100 99,HCD,LFEP
1,AB15,41633,CYDALQK,7,99.1,99.1,7,753.41852,2,106.8556,0.00,NaN,1504.8206,1.3,Carbamidomethylation; TMT16plex,100 99 100 99 99 98 99,HCD,CYDALQK
2,AB15,4223,KDVEDEQEH,9,99.0,99.0,9,868.95190,2,17.2993,0.00,NaN,1735.8873,1.1,TMT16plex,93 100 100 100 100 100 99 100 100,HCD,KDVEDEQEH
3,AB15,172562,HLDVGGHMY,9,99.0,99.9,9,444.89423,3,498.4120,-1.10,NaN,1331.6617,-0.6,TMT16plex,100 100 100 100 100 100 100 100 100,HCD,HLDVGGHMY
4,AB15,166861,EEVEVYRH,8,98.9,99.7,8,455.57578,3,485.2783,-1.21,NaN,1363.7057,-0.1,TMT16plex,100 100 100 100 100 100 99 99,HCD,EEVEVYRH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1487,MM01,30494,TAATPET,7,60.1,74.4,7,497.77191,2,108.9876,-19.18,NaN,993.5303,-1.1,TMT16plex,63 73 89 96 47 60 92,HCD,TAATPET
1488,MM01,161208,LEEYVTPQLSL,11,60.1,68.1,11,798.44672,2,488.8695,-15.67,NaN,1594.8778,0.6,TMT16plex,75 81 87 80 95 86 24 26 29 76 91,HCD,LEEYVTPQLSL
1489,MM01,64227,DRVE,4,60.0,60.0,4,411.73389,2,214.5730,0.00,NaN,821.4568,-4.3,TMT16plex,91 27 44 79,HCD,DRVE
1490,MM01,63966,QSDPTQSGMY,10,60.0,67.0,10,709.33429,2,213.8160,14.86,NaN,1416.6516,1.7,TMT16plex,26 27 58 58 64 66 87 89 96 98,HCD,QSDPTQSGMY
1491,MM01,133580,NPPLLSLE,8,60.0,70.8,8,593.85358,2,412.2195,17.40,NaN,1185.6930,-0.3,TMT16plex,51 41 55 72 78 76 95 98,HCD,NPPLLSLE

In [109]:
#save all the peaks peptides to file

peaks_peptides = peaks[['Peaks_Peptide']].rename(columns = {'Peaks_Peptide':'Peptide'}).drop_duplicates()

#peaks_peptides.to_csv('PEAKS_peptidelist.csv')

In [30]:
#merge the PEAKS with the p30 filtered df

merge = pd.merge(
    p30_filtered,
    peaks1,
    how = 'left',
    on = ['File','Spectrum_ID']
)

merge
#merge.to_excel('p30merge_PSM_PEAKS.xlsx')

,Sample,Spectrum,Peptide,Type,Length_x,Engine,PEPscore,FDR,Delta,UnambiguousMatch,...,z,RT,Delta RT,Area,Mass,ppm,PTM,local confidence (%),mode,tag(>=0.0%)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,530.5596,2.40,NaN,1009.5405,0.4,TMT16plex,69 62 73 59 70 86,HCD,ASETWL
1,20220420_MM,20220420_MM_68440,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.028707,0.001514,0.494802,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AB18,AB18_111709,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.048350,0.001954,0.423707,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AB18,AB18_111513,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.050874,0.001466,0.691760,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AB15_HORMAD,AB15_HORMAD_181255,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.023348,0.002185,0.495534,True,...,1.0,516.3840,-3.06,NaN,1103.6511,-0.7,TMT16plex,83 84 86 82 81 85 83 79 86,HCD,AEAAVVAVA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985,AB18,AB18_115245,VEDPVTVEY,REF,9.0,"mergedresults,comet",0.000734,0.000295,0.740285,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2986,AB19,AB19_266571,VEDPVTVEY,REF,9.0,"mergedresults,comet",0.000124,0.000139,0.522088,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987,AB15_HORMAD,AB15_HORMAD_185903,ALDSTNVEL,REF,9.0,"mergedresults,comet",0.000887,0.000915,0.626719,True,...,1.0,525.7846,-0.98,NaN,1264.6835,-0.5,TMT16plex,84 77 90 86 77 62 78 96 99 99,HCD,ALDSTGGVEL
2988,AB19,AB19_223326,ALDSTNVEL,REF,9.0,"mergedresults,comet",0.001054,0.000139,0.398766,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2989,AB16,AB16_110570,ALDSTNVEL,REF,9.0,"mergedresults,comet",0.001270,0.000265,0.715195,True,...,1.0,382.4090,-8.66,NaN,1264.6835,-1.4,TMT16plex,79 70 84 81 79 74 91 95 95,HCD,ALDSTNVEL

In [33]:
#mapping the peaks file to the psm files to see if novel or not?

peaks_match = pd.merge(
    main_psm,
    peaks,
    how = 'right',
    on = ['File','Spectrum_ID','Peptide']
)

#peaks_match.to_excel('Peaks_PSMmapped.xlsx')

In [28]:
#adding the peaks findings to the mapped p30 filtered files

peaks_psm_p30 = pd.merge(
    p30_mapping,
    peaks1,
    how = 'left',
    on = ['Spectrum_ID','File']
)

In [37]:
peaks_psm_p30
#peaks_psm_p30.to_excel('peaks+psm_p30filtered.xlsx')

,Sample,Spectrum,Peptide,Type,Length_x,Engine,PEPscore,FDR,Delta,UnambiguousMatch,...,z,RT,Delta RT,Area,Mass,ppm,PTM,local confidence (%),mode,tag(>=0.0%)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,530.5596,2.40,NaN,1009.5405,0.4,TMT16plex,69 62 73 59 70 86,HCD,ASETWL
1,20220420_MM,20220420_MM_68440,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.028707,0.001514,0.494802,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AB18,AB18_111709,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.048350,0.001954,0.423707,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AB18,AB18_111513,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.050874,0.001466,0.691760,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AB15_HORMAD,AB15_HORMAD_181255,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.023348,0.002185,0.495534,True,...,1.0,516.3840,-3.06,NaN,1103.6511,-0.7,TMT16plex,83 84 86 82 81 85 83 79 86,HCD,AEAAVVAVA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
#now to categorise the clusters to subcategories

print(merge.columns)

#lets clean up and only choose relevant details

clean_merge = merge[['Cluster_ID','Peptide','Type','PEPscore',
                            'FDR','Delta','Peaks_Peptide','SCORE (%)','ALC (%)',
                            'FileCount','Spectrum_ID','File','Cluster_Size']]

#now let's work with just this
clean_merge

Index(['Sample', 'Spectrum', 'Peptide', 'Type', 'Length_x', 'Engine',
       'PEPscore', 'FDR', 'Delta', 'UnambiguousMatch', 'Conflict',
       'Annotation', 'Database', 'Search', 'Charge', 'Proteins', 'File',
       'Spectrum_ID', 'Cluster_ID', 'FileCount', 'Cluster_Size',
       'Peaks_Peptide', 'Tag length', 'SCORE (%)', 'ALC (%)', 'Length_y',
       'm/z', 'z', 'RT', 'Delta RT', 'Area', 'Mass', 'ppm', 'PTM',
       'local confidence (%)', 'mode', 'tag(>=0.0%)'],
      dtype='object')

,Cluster_ID,Peptide,Type,PEPscore,FDR,Delta,Peaks_Peptide,SCORE (%),ALC (%),FileCount,Spectrum_ID,File,Cluster_Size
0,5075,NaN,NaN,NaN,NaN,NaN,ASETWL,69.1,69.8,6,188249,AB15,9
1,4563,AEAAVVAVA,REF,0.028707,0.001514,0.494802,NaN,NaN,NaN,6,68440,MM01,13
2,4563,AEAAVVAVA,REF,0.048350,0.001954,0.423707,NaN,NaN,NaN,6,111709,AB18,13
3,4563,AEAAVVAVA,REF,0.050874,0.001466,0.691760,NaN,NaN,NaN,6,111513,AB18,13
4,4563,AEAAVVAVA,REF,0.023348,0.002185,0.495534,AEAAVVAVA,82.4,83.4,6,181255,AB15,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985,4878,VEDPVTVEY,REF,0.000734,0.000295,0.740285,NaN,NaN,NaN,4,115245,AB18,4
2986,4878,VEDPVTVEY,REF,0.000124,0.000139,0.522088,NaN,NaN,NaN,4,266571,AB19,4
2987,4893,ALDSTNVEL,REF,0.000887,0.000915,0.626719,ALDSTGGVEL,84.1,84.7,4,185903,AB15,6
2988,4893,ALDSTNVEL,REF,0.001054,0.000139,0.398766,NaN,NaN,NaN,4,223326,AB19,6
2989,4893,ALDSTNVEL,REF,0.001270,0.000265,0.715195,ALDSTNVEL,80.3,83.2,4,110570,AB16,6

In [39]:
#let's check how many clusters and novel peptides found there are in 4-6 files

cluster_count = clean_merge['Cluster_ID'].nunique()

print('Number of filtered clusters for p30 in 4-6 files:', cluster_count)


#check the number of peptides in this clusters
peptide_count = clean_merge[['Cluster_ID','Peptide','Type']].drop_duplicates()

peptide_count = peptide_count['Type'].value_counts()

print('Type of peptides:',peptide_count)

Number of filtered clusters for p30 in 4-6 files: 364
Type of peptides: Type
REF      250
NOV       40
DECOY      3
Name: count, dtype: int64

In [40]:
#now let's categorise into fully identified and unidentified
#first maybe we can rename the peptides into identified and unidentified?

group = clean_merge.groupby(by='Cluster_ID').count().reset_index()

group

,Cluster_ID,Peptide,Type,PEPscore,FDR,Delta,Peaks_Peptide,SCORE (%),ALC (%),FileCount,Spectrum_ID,File,Cluster_Size
0,1558,21,21,21,21,21,5,5,5,21,21,21,21
1,1719,8,8,8,8,8,1,1,1,8,8,8,8
2,1787,14,14,14,14,14,2,2,2,14,14,14,14
3,1789,4,4,4,4,4,2,2,2,4,4,4,4
4,1792,5,5,5,5,5,1,1,1,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,20002,0,0,0,0,0,0,0,0,15,15,15,15
360,20204,0,0,0,0,0,0,0,0,10,10,10,10
361,20256,0,0,0,0,0,0,0,0,6,6,6,6
362,20275,0,0,0,0,0,0,0,0,5,5,5,5
363,21395,0,0,0,0,0,0,0,0,13,13,13,13

In [57]:
#now we can say those with clusters of 0 peptides as fully unid
unid = group.loc[group['Peptide']==0]

unid_clusters = unid[['Cluster_ID']]

print(unid_clusters)

unid_file = pd.merge(
    clean_merge,
    unid_clusters,
    how = 'right',
    on = 'Cluster_ID'
)

#unid_file.to_excel('p30_fully_unidentified.xlsx')
#unid_file.to_csv('fully_unidentified_p30.csv')

print('unidentified clusters = ', len(unid_clusters))

     Cluster_ID
8          1844
11         1888
12         1912
17         2176
18         2198
..          ...
359       20002
360       20204
361       20256
362       20275
363       21395

[93 rows x 1 columns]

In [58]:
#to get rid of all the clusters that are fully unidentified

filter_unid = clean_merge[~clean_merge.Cluster_ID.isin(unid_file.Cluster_ID)]

filter_unid

,Cluster_ID,Peptide,Type,PEPscore,FDR,Delta,Peaks_Peptide,SCORE (%),ALC (%),FileCount,Spectrum_ID,File,Cluster_Size
1,4563,AEAAVVAVA,REF,0.028707,0.001514,0.494802,NaN,NaN,NaN,6,68440,MM01,13
2,4563,AEAAVVAVA,REF,0.048350,0.001954,0.423707,NaN,NaN,NaN,6,111709,AB18,13
3,4563,AEAAVVAVA,REF,0.050874,0.001466,0.691760,NaN,NaN,NaN,6,111513,AB18,13
4,4563,AEAAVVAVA,REF,0.023348,0.002185,0.495534,AEAAVVAVA,82.4,83.4,6,181255,AB15,13
5,4563,AEAAVVAVA,REF,0.014815,0.000267,0.565873,NaN,NaN,NaN,6,262919,AB19,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985,4878,VEDPVTVEY,REF,0.000734,0.000295,0.740285,NaN,NaN,NaN,4,115245,AB18,4
2986,4878,VEDPVTVEY,REF,0.000124,0.000139,0.522088,NaN,NaN,NaN,4,266571,AB19,4
2987,4893,ALDSTNVEL,REF,0.000887,0.000915,0.626719,ALDSTGGVEL,84.1,84.7,4,185903,AB15,6
2988,4893,ALDSTNVEL,REF,0.001054,0.000139,0.398766,NaN,NaN,NaN,4,223326,AB19,6
2989,4893,ALDSTNVEL,REF,0.001270,0.000265,0.715195,ALDSTNVEL,80.3,83.2,4,110570,AB16,6

In [59]:
#now let's group the number of peptides per cluster

peptide_filter = filter_unid.groupby(by='Cluster_ID').nunique().reset_index()


#for fully identified clusters
id = peptide_filter.loc[peptide_filter['Peptide']==1] #this would mean all the clusters that only have 1 peptides, but this could also mean blank+1 peptide (partial)

id1 = id[['Cluster_ID']]

In [45]:
id

,Cluster_ID,Peptide,Type,PEPscore,FDR,Delta,Peaks_Peptide,SCORE (%),ALC (%),FileCount,Spectrum_ID,File,Cluster_Size
0,1558,1,1,21,10,21,1,5,4,1,21,4,1
1,1719,1,1,8,7,8,1,1,1,1,8,6,1
3,1789,1,1,4,4,4,1,2,2,1,4,4,1
4,1792,1,1,5,5,5,1,1,1,1,5,4,1
5,1797,1,1,7,5,7,1,2,2,1,7,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,13764,1,1,5,5,5,0,0,0,1,5,4,1
267,13943,1,1,5,4,5,0,0,0,1,5,4,1
268,16280,1,1,9,5,9,1,5,5,1,9,4,1
269,16336,1,1,7,4,7,1,1,1,1,7,4,1
270,16355,1,1,5,4,5,1,1,1,1,5,4,1

In [46]:
#extract the cluster list
id1

     Cluster_ID
0          1558
1          1719
3          1789
4          1792
5          1797
..          ...
266       13764
267       13943
268       16280
269       16336
270       16355

[254 rows x 1 columns]

In [60]:
#now to extract all of the identified and partially identified clusters out

iden_file = pd.merge(
    filter_unid,
    id1,
    how = 'right',
    on = 'Cluster_ID'
)

In [72]:
#let's filter out for the partially identified clusters

partial = iden_file[iden_file['Peptide'].isna()]

par_cluster = partial[['Cluster_ID']].drop_duplicates()

print('Partially Identified clusters = ',len(par_cluster))

Partially Identified clusters =  17

In [63]:
#extract out the partially identified clusters
par = pd.merge(
    par_cluster,
    iden_file,
    how = 'left',
    on = 'Cluster_ID'
)

#par.to_excel('p30_partialclusters.xlsx')

In [70]:
#now for the fully identified we can just filter out

identified = iden_file[~iden_file.Cluster_ID.isin(par.Cluster_ID)]

#identified.to_excel('p30_fully_identified.xlsx')

id_clust = identified[['Cluster_ID']].drop_duplicates()

print('fully identified clusters =',len(id_clust))

fully identified clusters = 237

In [78]:
#now we look at mismatches, but need to get rid of all id and partial
filter_id = filter_unid[~filter_unid.Cluster_ID.isin(iden_file.Cluster_ID)]

filter_id #now the current working df, and this is the file with all mismatches

#filter_id.to_excel('p30_mismatchclusters.xlsx')

In [84]:
#find the number of mismatch clusters

mis = filter_id[['Cluster_ID']].drop_duplicates()

print('mismatch clusters =', len(mis))

mismatch clusters = 17

In [89]:
#mismatch categories

peptide_mis = filter_id.groupby('Cluster_ID').nunique().reset_index()

peptide_mis

,Cluster_ID,Peptide,Type,PEPscore,FDR,Delta,Peaks_Peptide,SCORE (%),ALC (%),FileCount,Spectrum_ID,File,Cluster_Size
0,1787,2,2,14,5,14,1,2,2,1,14,4,1
1,2116,2,1,5,5,5,2,2,2,1,9,4,1
2,4029,3,2,8,8,8,2,4,4,1,8,4,1
3,4326,2,2,8,8,8,1,4,4,1,8,4,1
4,4413,2,2,5,5,5,2,4,4,1,6,4,1
5,4571,3,2,7,7,7,0,0,0,1,7,6,1
6,4650,2,1,5,5,5,1,3,3,1,5,4,1
7,4742,2,1,4,4,4,1,2,2,1,5,4,1
8,4768,2,1,2,2,2,1,5,5,1,15,4,1
9,4799,2,1,4,4,4,0,0,0,1,8,4,1
10,4801,2,2,9,9,9,1,3,3,1,9,4,1
11,4864,2,1,4,4,4,2,2,2,1,4,4,1
12,5009,2,1,2,2,2,0,0,0,1,5,4,1
13,5394,3,1,3,3,3,1,2,2,1,5,4,1
14,6218,3,2,7,6,7,1,1,1,1,8,4,1
15,9465,3,2,4,4,4,1,2,2,1,4,4,1
16,9656,2,1,6,6,6,1,2,2,1,6,4,1

In [91]:
#for those with unidentified
mis_unid = filter_id[filter_id['Peptide'].isna()]
mis_unid1 = mis_unid[['Cluster_ID']].drop_duplicates()

print('mismatch with unid =', len(mis_unid1))

mismatch with unid = 8

In [93]:
#for those remaining, filter out those NaN
filter_mis = filter_id[~filter_id.Cluster_ID.isin(mis_unid1.Cluster_ID)]

filter_mis #use this next

,Cluster_ID,Peptide,Type,PEPscore,FDR,Delta,Peaks_Peptide,SCORE (%),ALC (%),FileCount,Spectrum_ID,File,Cluster_Size
51,4571,AMAAVVVAA,REF,0.288176,0.044199,0.288581,NaN,NaN,NaN,6,69045,ZK01,7
52,4571,AMAAVVVAA,REF,0.218419,0.024018,0.243726,NaN,NaN,NaN,6,68255,MM01,7
53,4571,AMAAVVVAA,REF,0.218139,0.033181,0.051500,NaN,NaN,NaN,6,262786,AB19,7
54,4571,AMAAVVVAA,REF,0.293512,0.048707,0.156396,NaN,NaN,NaN,6,111614,AB18,7
55,4571,ALCVVAVA,NOV,0.157599,0.024223,0.032699,NaN,NaN,NaN,6,105681,AB16,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2935,4801,SEAAYTLGP,REF,0.087586,0.005306,0.561482,SEASFTPVA,66.2,81.9,4,151662,AB18,9
2936,4801,SEASFPSLA,NOV,0.076753,0.007879,0.037279,NaN,NaN,NaN,4,379601,AB19,9
2937,4801,SEAAYTLGP,REF,0.044035,0.002449,0.153371,NaN,NaN,NaN,4,425720,AB19,9
2938,4801,SEASFPSLA,NOV,0.099446,0.009293,0.007585,NaN,NaN,NaN,4,189951,AB18,9
2950,4864,AADEPVTVL,REF,0.004561,0.000295,0.658222,NaN,NaN,NaN,4,115483,AB18,4

In [98]:
#for peptide count again
peptide_mis1 = filter_mis.groupby('Cluster_ID').nunique().reset_index()

peptide_mis1

#for 2 peptides
A = peptide_mis1.loc[peptide_mis1['Peptide']==2]
print('Mismatch with 2 peptides =', len(A))

#for 3 peptides
B = peptide_mis1.loc[peptide_mis1['Peptide']==3]
print('Mismatch with 3 peptides =', len(B))

Mismatch with 2 peptides = 6
Mismatch with 3 peptides = 3

In [101]:
##Now to go back to the matrix, working with p30 file first

p30 = p30_mapping

p30 #use this to work with the clusters

,Sample,Spectrum,Peptide,Type,Length,Engine,PEPscore,FDR,Delta,UnambiguousMatch,...,Annotation,Database,Search,Charge,Proteins,File,Spectrum_ID,Cluster_ID,FileCount,Cluster_Size
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB15,188249,5075,6,9
1,20220420_MM,20220420_MM_68440,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.028707,0.001514,0.494802,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","ERV_UP_8,gencode_pc_transcripts_0,Human+Ecoli_...",V1,1.0,"sp_Q8IZQ5_SELH_HUMAN,UTR5_ENSG00000211450_ENST...",MM01,68440,4563,6,13
2,AB18,AB18_111709,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.048350,0.001954,0.423707,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","gencode_pc_transcripts_1,gencode_pc_transcript...",V1,1.0,"sp_Q8IZQ5_SELH_HUMAN,1_ENST00000534355_ENSG000...",AB18,111709,4563,6,13
3,AB18,AB18_111513,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.050874,0.001466,0.691760,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","gencode_pc_transcripts_1,gencode_pc_transcript...",V1,1.0,"sp_Q8IZQ5_SELH_HUMAN,1_ENST00000534355_ENSG000...",AB18,111513,4563,6,13
4,AB15_HORMAD,AB15_HORMAD_181255,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.023348,0.002185,0.495534,True,...,".(iTRAQ8plex)AEAAVVAVA,n[+304.205359999999985]...","GSE143263_nuORFdb_v1.0.aa.lorf,gencode_pc_tran...",V1,1.0,"ENST00000534355.5_1_11:57508824-57509287:+_1,E...",AB15,181255,4563,6,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB18,301730,17618,2,14
48354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB19,573799,17618,2,14
48355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB19,574407,17618,2,14
48356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AB19,555389,17618,2,14
48357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ZK01,166578,67289,2,2

In [105]:
#create a merge of p30 mapping with peaks

merge2 = pd.merge(
    p30_mapping,
    peaks1,
    how = 'left',
    on = ['File','Spectrum_ID']
)

merge2

,Sample,Spectrum,Peptide,Type,Length_x,Engine,PEPscore,FDR,Delta,UnambiguousMatch,...,z,RT,Delta RT,Area,Mass,ppm,PTM,local confidence (%),mode,tag(>=0.0%)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,530.5596,2.40,NaN,1009.5405,0.4,TMT16plex,69 62 73 59 70 86,HCD,ASETWL
1,20220420_MM,20220420_MM_68440,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.028707,0.001514,0.494802,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AB18,AB18_111709,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.048350,0.001954,0.423707,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AB18,AB18_111513,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.050874,0.001466,0.691760,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AB15_HORMAD,AB15_HORMAD_181255,AEAAVVAVA,REF,9.0,"mergedresults,comet",0.023348,0.002185,0.495534,True,...,1.0,516.3840,-3.06,NaN,1103.6511,-0.7,TMT16plex,83 84 86 82 81 85 83 79 86,HCD,AEAAVVAVA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
#cleaner version of the merge2

clean_merge2 = merge2[['Cluster_ID','Peptide','Type','PEPscore',
                            'FDR','Delta','Peaks_Peptide','SCORE (%)','ALC (%)',
                            'FileCount','Spectrum_ID','File','Cluster_Size']]

#now let's work with just this
clean_merge2

,Cluster_ID,Peptide,Type,PEPscore,FDR,Delta,Peaks_Peptide,SCORE (%),ALC (%),FileCount,Spectrum_ID,File,Cluster_Size
0,5075,NaN,NaN,NaN,NaN,NaN,ASETWL,69.1,69.8,6,188249,AB15,9
1,4563,AEAAVVAVA,REF,0.028707,0.001514,0.494802,NaN,NaN,NaN,6,68440,MM01,13
2,4563,AEAAVVAVA,REF,0.048350,0.001954,0.423707,NaN,NaN,NaN,6,111709,AB18,13
3,4563,AEAAVVAVA,REF,0.050874,0.001466,0.691760,NaN,NaN,NaN,6,111513,AB18,13
4,4563,AEAAVVAVA,REF,0.023348,0.002185,0.495534,AEAAVVAVA,82.4,83.4,6,181255,AB15,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48353,17618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,301730,AB18,14
48354,17618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,573799,AB19,14
48355,17618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,574407,AB19,14
48356,17618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,555389,AB19,14
48357,67289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,166578,ZK01,2

In [120]:
#to check how many total clusters per file
totalclust = clean_merge2.groupby(by='Cluster_ID').nunique().reset_index()

#printing the values
two = totalclust.loc[totalclust['File']==2]
three = totalclust.loc[totalclust['File']==3]
four = totalclust.loc[totalclust['File']==4]
five = totalclust.loc[totalclust['File']==5]
six = totalclust.loc[totalclust['File']==6]

print(
    '2 clusters =', len(two),
    '3 clusters =', len(three),
    '4 clusters =', len(four),
    '5 clusters =', len(five),
    '6 clusters =', len(six),
    )

2 clusters = 12059 3 clusters = 939 4 clusters = 309 5 clusters = 34 6 clusters = 21

In [112]:
#now let's categorise into fully identified and unidentified
#first maybe we can rename the peptides into identified and unidentified?

group1 = clean_merge2.groupby(by='Cluster_ID').count().reset_index()
group1

,Cluster_ID,Peptide,Type,PEPscore,FDR,Delta,Peaks_Peptide,SCORE (%),ALC (%),FileCount,Spectrum_ID,File,Cluster_Size
0,1288,0,0,0,0,0,0,0,0,10,10,10,10
1,1300,0,0,0,0,0,0,0,0,10,10,10,10
2,1492,0,0,0,0,0,0,0,0,3,3,3,3
3,1502,3,3,3,3,3,1,1,1,3,3,3,3
4,1504,5,5,5,5,5,1,1,1,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13357,67269,0,0,0,0,0,0,0,0,2,2,2,2
13358,67270,0,0,0,0,0,0,0,0,2,2,2,2
13359,67271,0,0,0,0,0,0,0,0,2,2,2,2
13360,67288,0,0,0,0,0,0,0,0,2,2,2,2
13361,67289,0,0,0,0,0,0,0,0,2,2,2,2

In [109]:
#now we can say those with clusters of 0 peptides as fully unid
unid1 = group1.loc[group1['Peptide']==0]

unid_clusters1 = unid1[['Cluster_ID']]

print(unid_clusters1)

unid_file1 = pd.merge(
    clean_merge2,
    unid_clusters1,
    how = 'right',
    on = 'Cluster_ID'
)

       Cluster_ID
0            1288
1            1300
2            1492
6            1509
10           1519
...           ...
13357       67269
13358       67270
13359       67271
13360       67288
13361       67289

[8868 rows x 1 columns]
unidentified clusters =  8868

In [110]:
unid1

,Cluster_ID,Peptide,Type,PEPscore,FDR,Delta,Peaks_Peptide,SCORE (%),ALC (%),FileCount,Spectrum_ID,File,Cluster_Size
0,1288,0,0,0,0,0,0,0,0,10,10,10,10
1,1300,0,0,0,0,0,0,0,0,10,10,10,10
2,1492,0,0,0,0,0,0,0,0,3,3,3,3
6,1509,0,0,0,0,0,0,0,0,2,2,2,2
10,1519,0,0,0,0,0,1,1,1,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13357,67269,0,0,0,0,0,0,0,0,2,2,2,2
13358,67270,0,0,0,0,0,0,0,0,2,2,2,2
13359,67271,0,0,0,0,0,0,0,0,2,2,2,2
13360,67288,0,0,0,0,0,0,0,0,2,2,2,2
13361,67289,0,0,0,0,0,0,0,0,2,2,2,2

In [ ]:
#unid_file.to_excel('p30_fully_unidentified.xlsx')
#unid_file.to_csv('fully_unidentified_p30.csv')

print('unidentified clusters = ', len(unid_clusters1))